const throwError = () => {
  throw new Error("this will cause the test to fail");
};

module.exports = { throwError };
